### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [chardet/chardet#95] opened 2017-01-16 14:37 UTC
Latest release is very old - 2014-10-07. There are some useful updates since this date.

**Comment by sigmavirus24** [comment] 2017-01-16 20:42
This is a duplicate of #83

**Comment by sigmavirus24** [comment] 2017-01-16 20:42
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2017-01-16 20:42 UTC
